# syntax=docker/dockerfile:1.7-labs
FROM docker.io/ros:iron-ros-base

# This env variable is used by tools
ENV SOURCE_DIRECTORY /ros2_ws

# Install minimal requirements for nodes
ENV DEBIAN_FRONTEND noninteractive
RUN apt update -y \
	&& apt upgrade -y --no-install-recommends \
	&& apt install -y --no-install-recommends \
		wget \
		sqlite3 \
		ros-iron-foxglove-bridge \
		ros-iron-cv-bridge \
		python3-pip \
		python3-pyproj \
		python3-ujson \
	&& rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install  \
		flask \
		flask-cors \
		yq 

RUN mkdir /ros2_ws
COPY build /ros2_ws
COPY --parents clean_repo/./adore_scenarios /ros2_ws
COPY --parents clean_repo/./tools/adore_api /ros2_ws
COPY clean_repo/setup.sh /ros2_ws
COPY clean_repo/adore.env /ros2_ws
COPY clean_repo/tools/check_adore_binaries.sh /ros2_ws/tools/check_adore_binaries.sh
COPY clean_repo/tools/adore_release/files/entrypoint.sh /entrypoint.sh
COPY clean_repo/tools/adore_release/files/README.md /ros2_ws/
COPY clean_repo/tools/adore_release/files/LICENSE /ros2_ws/
COPY clean_repo/tools/adore_release/files/NOTICE.md /ros2_ws/

WORKDIR /ros2_ws
ENTRYPOINT /entrypoint.sh
