name: ADORe Reusable Workflow

on:
  workflow_call:
    inputs:
      platform:
        description: 'Runner name'
        required: true
        type: string
      archive_name:
        description: 'Name of the uploaded build archive'
        required: true
        type: string
      image_platform:
        description: 'Docker compatible platform reference'
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.platform }}

    steps:
      - name: Init
        shell: bash
        run: |
          df -h
          sudo apt update -y

      - name: Disable man-db to make package install and removal faster
        shell: bash
        # From https://github.com/jlumbroso/free-disk-space/issues/40
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
          sudo dpkg-reconfigure man-db

      - name: Maximize free space
        id: maximize-space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Freespace Check
        shell: bash
        run: |
          df -h
          REQUIRED_FREE_SPACE=25
          free_space=$(df -h . | awk '{print $4}' | grep "G")
          free_space="${free_space%G}"
          if [ -z "$free_space" ]; then
              echo "ERROR: free_space variable is empty or not set." >&2
              exit 1
          fi
          df -h
          echo "Free space (required): ${REQUIRED_FREE_SPACE} GB"
          echo "Free space (available): ${free_space} GB"
          if (( REQUIRED_FREE_SPACE > free_space )); then
              echo "ERROR: Insufficient free space: ${free_space} GB available, ${REQUIRED_FREE_SPACE} GB required." >&2
              exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          submodules: 'recursive'

      - name: Install requirements
        shell: bash
        run: |
          df -h
          sudo apt update -y
          sudo apt install -y make curl jq

      - name: Build vendor libraries
        shell: bash
        run: |
          echo "Building vendor..."
          make build_vendor_libraries 
          #make save || true

      - name: Build ADORe CLI
        shell: bash
        run: |
          echo "Building ADORe CLI..."
          make build_adore_cli
          #make save || true

      - name: Test ROS2 installation
        shell: bash
        run: |
          echo "Testing the ROS 2 installation in the ADORe CLI..."
          #make load || true
          make test_ros2_installation
          #make save || true

      - name: Build user libraries
        shell: bash
        run: |
          #make load || true
          echo "Building user libraries..."
          make build_libraries
          #make save || true

      - name: Build ROS nodes
        shell: bash
        run: |
          #make load || true
          echo "Building ROS nodes..."
          make build_nodes
          #make save || true

      - name: Build Services
        shell: bash
        run: |
          #make load || true
          echo "Building services..."
          make build_services
          #make save || true

      - name: CI Test
        shell: bash
        run: |
          df -h
          make save || true
          make ci_test
      
      - name: Documentation Lint
        shell: bash
        run: |
          cd documentation
          make lint
      
      - name: Create logs archive
        shell: bash
        run: |
          if [ -d ".log" ]; then
            tar -czf logs_${{ runner.arch }}.tar.gz .log/
            echo "Archive created: logs_${{ runner.arch }}.tar.gz"
          else
            echo "Warning: .log directory not found for archiving"
            touch logs_${{ runner.arch }}.tar.gz
          fi

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs_${{ runner.arch }}
          path: logs_${{ runner.arch }}.tar.gz
      
      - name: Create build archive
        shell: bash
        run: |
          tar --create --auto-compress --preserve-permissions --file=adore_${{ inputs.archive_name }}.txz \
            ros2_workspace/install/*

      - name: List package
        shell: bash
        run: |
          ls -lah

      - name: Upload build archive
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ inputs.archive_name }}
          if-no-files-found: error
          path: |
            adore_${{ inputs.archive_name }}.txz

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    # Only create a release on a push, not for other events
    if: github.event_name == 'push'

    permissions:
      contents: write
      actions: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          path: clean_repo
          submodules: 'recursive'

      - name: Download build archive
        uses: actions/download-artifact@v4
        with:
          name: build-${{ inputs.archive_name }}

      - name: Unpack build archive
        shell: bash
        run: |
          mkdir -p build
          ls -lah
          tar --extract --preserve-permissions --file=adore_${{ inputs.archive_name }}.txz --directory=build
          ls -lah build
          ls -lah clean_repo

      - name: Get clean branch name
        shell: bash
        # From https://github.com/DLR-TS/make_gadgets/blob/master/tools/branch_name.sh
        run: echo "BUILD_BRANCH=$(echo ${{ github.ref_name }} | tr -d '[:space:]' | tr -s -c "[:alnum:][:blank:]\.\_\-" _ | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Create release archive
        shell: bash
        run: |
          tar --create --preserve-permissions --file=adore_latest.tar --directory build .
          tar --append --preserve-permissions --file=adore_latest.tar --directory clean_repo \
            adore_scenarios \
            tools/adore_api \
            setup.sh \
            README.md \
            NOTICE.md \
            LICENSE
          xz --to-stdout adore_latest.tar > adore_${BUILD_BRANCH}_latest_${{ inputs.archive_name }}.txz

      - name: List package
        shell: bash
        run: |
          ls -lah

      - name: Release
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          files: |
            adore_*_latest_${{ inputs.archive_name }}.txz

  image:
    name: Image
    runs-on: ${{ inputs.platform }}
    needs: build

    # Only create a release on a push, not for other events
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          path: clean_repo
          submodules: 'recursive'

      - name: Download build archive
        uses: actions/download-artifact@v4
        with:
          name: build-${{ inputs.archive_name }}

      - name: Unpack build archive
        shell: bash
        run: |
          mkdir -p build
          ls -lah
          tar --extract --preserve-permissions --file=adore_${{ inputs.archive_name }}.txz --directory=build
          ls -lah build
          ls -lah clean_repo

      - name: Get clean branch name
        shell: bash
        # From https://github.com/DLR-TS/make_gadgets/blob/master/tools/branch_name.sh
        run: echo "BUILD_BRANCH=$(echo ${{ github.ref_name }} | tr -d '[:space:]' | tr -s -c "[:alnum:][:blank:]\.\_\-" _ | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build image
        shell: bash
        run: |
          docker build --file=clean_repo/tools/adore_release/Containerfile --tag adore:${BUILD_BRANCH}-${{ inputs.image_platform }} --build-arg ARCH=${{ inputs.image_platform }} .
          docker image tag adore:${BUILD_BRANCH}-${{ inputs.image_platform }} ghcr.io/${{ github.repository_owner }}/adore:${BUILD_BRANCH}-${{ inputs.image_platform }}
          docker image ls -a

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker images
        shell: bash
        run: |
          docker image push ghcr.io/${{ github.repository_owner }}/adore:${BUILD_BRANCH}-${{ inputs.image_platform }}
        #make push_core_image
